CREATE USER 'btuser'@'localhost' IDENTIFIED BY 'password';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'btuser'@'localhost' WITH GRANT OPTION;

CREATE DATABASE IF EXISTS bugtracker;

